"""Add temperature and description to location table

Revision ID: a3ca5d83001c
Revises: 356c54a20d1c
Create Date: 2024-03-04 09:32:34.708054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ca5d83001c'
down_revision: Union[str, None] = '356c54a20d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'description')
    op.drop_column('locations', 'temperature')
    # ### end Alembic commands ###
