services:
  server:
    build:
      context: ./backend/
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    develop:
      watch:
        - action: rebuild
          path: ./backend/
#
# Frontend
#  client:
#    build:
#      context: ./frontend/
#    ports:
#      - 3000:80
#    develop:
#      watch:
#        - action: rebuild
#          path: ./frontend/

